# Generated by Django 4.1.1 on 2022-09-22 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=10)),
                ('status', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(choices=[('LAPTOP', 'Laptop'), ('MOUSE', 'Mouse'), ('KEYBOARD', 'Keyboard'), ('GAME', 'Game'), ('BOOK', 'Book'), ('SHIRT', 'Shirt'), ('PANTS', 'Pants'), ('TV', 'TV'), ('DVD', 'DVD')], max_length=8, verbose_name='item name')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SHIPPED', 'Shipped'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=9, verbose_name='order status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_lines', to='products.order')),
            ],
        ),
    ]
